#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid
# Display "To infinity and beyond" indefinitely
# Display "I hate the kill command" when receiving a SIGTERM
# Displays "Y U no love me?!" when receiving SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUI

finisher () {
		rm /var/run/myscript.pid
		exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && finsher' SIGTERM
	trap 'finsher' SIGQUIT
done
