#!/usr/bin/env bash
# Print To infinity and beyond indefinitely
# With sleep 2 into each iteration
# Print I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
