#!/usr/bin/env bash
# Display bad luck for the 4th iteration
# Display good luck for the 8th iteration
# Display Best School for other iteration
count=1
while [ $count -le 10 ];
do
	if [ $count -eq 4 ];
	then
		echo "bad luck"
	elif [ $count -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
